# Generated by Django 6.0.4 on 2026-04-12 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mpesa', 'M-Pesa Daraja'), ('paystack', 'Paystack'), ('paypal', 'PayPal')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Use sandbox/test credentials')),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=255)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=255)),
                ('mpesa_callback_url', models.URLField(blank=True)),
                ('paystack_public_key', models.CharField(blank=True, max_length=255)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=255)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.PositiveIntegerField(help_text='Number of message units this plan adds')),
                ('price_kes', models.DecimalField(decimal_places=2, help_text='Price in KES for M-Pesa', max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Price in USD for PayPal/Paystack', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paystack', 'Paystack'), ('paypal', 'PayPal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('units_purchased', models.PositiveIntegerField(default=0)),
                ('gateway_reference', models.CharField(blank=True, help_text='Gateway transaction ID', max_length=255)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('paystack_reference', models.CharField(blank=True, max_length=255)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='For M-Pesa STK push', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.pricingplan')),
            ],
        ),
    ]
