# Generated by Django 6.0.4 on 2026-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description shown on the pricing page'),
        ),
    ]
