# Generated by Django 6.0.4 on 2026-04-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('africas_talking', "Africa's Talking"), ('twilio', 'Twilio'), ('infobip', 'Infobip')], max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('username', models.CharField(help_text="Required for Africa's Talking", max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meta Cloud API', max_length=50)),
                ('access_token', models.CharField(max_length=500)),
                ('phone_number_id', models.CharField(max_length=100)),
                ('waba_id', models.CharField(max_length=100, verbose_name='WhatsApp Business Account ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
