# Generated by Django 6.0.4 on 2026-04-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The template name from Meta Dashboard', max_length=100)),
                ('category', models.CharField(default='MARKETING', max_length=50)),
                ('language_code', models.CharField(default='en_US', max_length=10)),
                ('body_text', models.TextField(help_text='Copy of the template text for reference')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='providers.whatsappprovider')),
            ],
        ),
    ]
