# Generated by Django 6.0.4 on 2026-04-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_whatsapptemplate'),
        ('providers', '0003_email_provider'),
    ]

    operations = [
    ]
