# Generated by Django 6.0.4 on 2026-04-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_clicks_count_campaign_design_json_and_more'),
        ('contacts_app', '0003_conversation_message'),
        ('providers', '0008_whatsapp_provider_fields_and_template_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='design_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='WhatsAppDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_delivery_logs', to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_delivery_logs', to='contacts_app.contact')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='providers.whatsappprovider')),
            ],
        ),
    ]
