# Generated by Django 6.0.4 on 2026-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_emailtemplate_design_json_emailtemplate_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short template description'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
