# Generated by Django 6.0.4 on 2026-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_emailtemplate_description_emailtemplate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'AI Provider Setting',
                'verbose_name_plural': 'AI Provider Settings',
            },
        ),
    ]
