# Generated by Django 6.0.4 on 2026-04-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_user'),
        ('providers', '0003_email_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.emailprovider'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.whatsapptemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.emailtemplate'),
        ),
    ]
