# Generated by Django 6.0.4 on 2026-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_add_campaign_provider_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='channel',
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='SMS'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
        ),
    ]
