# Generated by Django 6.0.4 on 2026-04-13 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_cancel_reason_alter_campaign_status'),
        ('providers', '0007_emailtemplate_owner_alter_emailtemplate_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.messagetemplate'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
