# Generated by Django 6.0.4 on 2026-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_description_campaign_sms_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failure_reason',
            field=models.TextField(blank=True, default='', help_text='Stores the most recent delivery failure details.'),
        ),
    ]
