# Generated by Django 6.0.4 on 2026-04-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_failure_reason'),
        ('contacts_app', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clicks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='design_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='opens_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_events', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_open_events', to='contacts_app.contact')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
